// <auto-generated />
using System;
using MediaDownloader.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaDownloader.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709144000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MediaDownloader.Data.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DesktopEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisabledProviders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailFrom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyOnComplete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOnStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NtfyServer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NtfyTopic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PostDownloadAction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SmtpUseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramBotToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramChatId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TelegramEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("MediaDownloader.Data.Entities.DownloadItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CompleteNotificationSent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MagnetUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NameIsPlaceholder")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Progress")
                        .HasColumnType("REAL");

                    b.Property<string>("SavePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("StartNotificationSent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TorrentFilePath")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InfoHash")
                        .IsUnique()
                        .HasFilter("\"InfoHash\" <> ''");

                    b.HasIndex("SeriesTaskId");

                    b.ToTable("Downloads");
                });

            modelBuilder.Entity("MediaDownloader.Data.Entities.ProviderCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName")
                        .IsUnique();

                    b.ToTable("ProviderCredentials");
                });

            modelBuilder.Entity("MediaDownloader.Data.Entities.SeriesTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadFolder")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndEpisode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastDownloadedEpisode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartEpisode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleFilter")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SeriesTasks");
                });

            modelBuilder.Entity("MediaDownloader.Data.Entities.DownloadItem", b =>
                {
                    b.HasOne("MediaDownloader.Data.Entities.SeriesTask", "SeriesTask")
                        .WithMany("Downloads")
                        .HasForeignKey("SeriesTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SeriesTask");
                });

            modelBuilder.Entity("MediaDownloader.Data.Entities.SeriesTask", b =>
                {
                    b.Navigation("Downloads");
                });
#pragma warning restore 612, 618
        }
    }
}
